version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-browsers
    steps:
      - checkout
      - run: echo "A first hello"
  build:
    docker:
      - image: circleci/python:2.7.15-browsers
    steps:
      - checkout
      - run: echo "A first hello" 
